---
# supervisor to run all services together

- name: install python pip
  apt: name={{ item }} state=present
  with_items:
    - python
    - python-pip
    - rsyslog


- name: install supervisor
  pip: name=supervisor state=present

- name: create config dir
  file: path=/etc/supervisor/conf.d state=directory

- name: setup config
  copy: src=supervisord.conf dest=/etc/supervisord.conf
