---
# setup of sqlite db
- name: install postamt deps
  apt: name={{ item }} state=present
  with_items:
    - python-dev
    - sqlite3

- name: install postamt
  pip: name=postamt state=latest

- name: create data
  file: path={{ data }} state=directory

- name: init db
  command: postamt init
